spring:
  config:
    activate:
      on-profile: accept

  data:
    mongodb:
      uri: "mongodb+srv://gagan:root@gkr-portfolio-cluster.ddorknt.mongodb.net/gkr_portfolio_accept?appName=GKR-Portfolio-Cluster"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:gagandarshan22@gmail.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  cors:
    allowed-origins:
      - https://gkr-portfolio.vercel.app # Update with proper prod/accept origin link
