spring:
  config:
    activate:
      on-profile: test

  data:
    mongodb:
      uri: "mongodb+srv://gagan:root@gkr-portfolio-cluster.ddorknt.mongodb.net/gkr_portfolio?appName=GKR-Portfolio-Cluster"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} #Add Email follewed by :abc@abc.com for local development
    password: ${MAIL_PASSWORD} #Add App Password follewed by :zzzzzzzzzzzzz for local development
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

gkr:
  util:
    mail: gkr.techie@gmail.com
  notification:
    service:
      url: https://gkr-notification-service.onrender.com/api/notifications/send