spring:
  config:
    activate:
      on-profile: accept

  data:
    mongodb:
      uri: "mongodb+srv://gagan:root@gkr-portfolio-cluster.ddorknt.mongodb.net/gkr_portfolio_accept?appName=GKR-Portfolio-Cluster"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:gkr.techie@gmail.com}
    password: ${MAIL_PASSWORD:bzjuxtyidgodycsp}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

gkr:
  util:
    mail: gagandarshan22@gmail.