spring:
  application:
    name: portfolio-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}

  data:
    mongodb:
      uri: "mongodb+srv://gagan:root@gkr-portfolio-cluster.ddorknt.mongodb.net/gkr_portfolio?appName=GKR-Portfolio-Cluster"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api/gkr