name: Keep Render Alive  # Free Render will shoutdown (DOWN) if it is not accessed for 15 mins, Hence when we come back after that tried to access it will take time to UP the backend

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render backend
        run: curl -sS -m 20 https://gkr-portfolio-backend-test.onrender.com/api/gkr/app/details > /dev/null